// <auto-generated />
using System;
using GeoGuide.Cms.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoGuide.Cms.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260416215054_AddSchemaGuardRailsFunction11")]
    partial class AddSchemaGuardRailsFunction11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoGuide.Cms.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TenantId");

                    b.ToTable("cms_users", (string)null);
                });

            modelBuilder.Entity("GeoGuide.Cms.Models.PlaybackLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_id");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trigger_type");

                    b.HasKey("Id");

                    b.HasIndex("PlayedAt");

                    b.HasIndex("PoiId");

                    b.ToTable("playback_logs", null, t =>
                        {
                            t.HasCheckConstraint("CK_playback_logs_duration_non_negative", "duration_seconds >= 0");

                            t.HasCheckConstraint("CK_playback_logs_trigger_type", "trigger_type IN ('gps', 'qr', 'manual')");
                        });
                });

            modelBuilder.Entity("GeoGuide.Cms.Models.Poi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer")
                        .HasColumnName("approval_status");

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_key");

                    b.Property<string>("CategoryLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category_label");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cooldown_minutes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MapUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("map_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TriggerRadiusMeters")
                        .HasColumnType("integer")
                        .HasColumnName("trigger_radius_meters");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("pois", null, t =>
                        {
                            t.HasCheckConstraint("CK_pois_cooldown_minutes_non_negative", "cooldown_minutes >= 0");

                            t.HasCheckConstraint("CK_pois_latitude_range", "latitude >= -90 AND latitude <= 90");

                            t.HasCheckConstraint("CK_pois_longitude_range", "longitude >= -180 AND longitude <= 180");

                            t.HasCheckConstraint("CK_pois_priority_non_negative", "priority >= 0");

                            t.HasCheckConstraint("CK_pois_trigger_radius_positive", "trigger_radius_meters > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f0bbf75-a9fc-4a94-93a1-7c5ef0fc6a01"),
                            ApprovalStatus = 1,
                            CategoryKey = "attraction",
                            CategoryLabel = "Tham quan",
                            CooldownMinutes = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Khu cho noi tieng o trung tam TP.HCM.",
                            ImageUrl = "https://images.unsplash.com/photo-1555921015-5532091f6026",
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 10.772,
                            Longitude = 106.6983,
                            MapUrl = "https://maps.google.com/?q=10.7720,106.6983",
                            Name = "Ben Thanh Market",
                            Priority = 1,
                            TenantId = new Guid("6eb3f509-c1a5-4d8d-9bb4-e307db6d0a75"),
                            TriggerRadiusMeters = 80,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("458a1a0e-b524-4e95-92f4-684e80ea7b97"),
                            ApprovalStatus = 1,
                            CategoryKey = "attraction",
                            CategoryLabel = "Tham quan",
                            CooldownMinutes = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Nha tho Duc Ba Sai Gon voi kien truc Phap tieu bieu.",
                            ImageUrl = "https://images.unsplash.com/photo-1583417267826-aebc4d1542e1",
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 10.7798,
                            Longitude = 106.699,
                            MapUrl = "https://maps.google.com/?q=10.7798,106.6990",
                            Name = "Notre-Dame Cathedral",
                            Priority = 2,
                            TenantId = new Guid("6eb3f509-c1a5-4d8d-9bb4-e307db6d0a75"),
                            TriggerRadiusMeters = 90,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5807657e-240d-42cb-b6e8-b46fd35652ce"),
                            ApprovalStatus = 1,
                            CategoryKey = "park",
                            CategoryLabel = "Cong vien",
                            CooldownMinutes = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Cong vien xanh phu hop cho di bo va thu gian.",
                            ImageUrl = "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 10.777799999999999,
                            Longitude = 106.6927,
                            MapUrl = "https://maps.google.com/?q=10.7778,106.6927",
                            Name = "Tao Dan Park",
                            Priority = 3,
                            TenantId = new Guid("6eb3f509-c1a5-4d8d-9bb4-e307db6d0a75"),
                            TriggerRadiusMeters = 100,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a76542f8-e34f-45ee-96c9-0e3961c4ca30"),
                            ApprovalStatus = 1,
                            CategoryKey = "museum",
                            CategoryLabel = "Bao tang",
                            CooldownMinutes = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bao tang gioi thieu lich su va van hoa thanh pho.",
                            ImageUrl = "https://images.unsplash.com/photo-1518998053901-5348d3961a04",
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 10.7765,
                            Longitude = 106.70099999999999,
                            MapUrl = "https://maps.google.com/?q=10.7765,106.7010",
                            Name = "Ho Chi Minh City Museum",
                            Priority = 4,
                            TenantId = new Guid("6eb3f509-c1a5-4d8d-9bb4-e307db6d0a75"),
                            TriggerRadiusMeters = 75,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("347dca58-717a-44cc-a470-0d12d2f039d1"),
                            ApprovalStatus = 1,
                            CategoryKey = "food-street",
                            CategoryLabel = "Am thuc",
                            CooldownMinutes = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Quan oc mo cua toi, phuc vu cac mon oc nuong, hap va xao ngay gan khu ky tuc xa.",
                            ImageUrl = "https://example.com/images/oc-vinh-khanh-198.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 10.7599,
                            Longitude = 106.68129999999999,
                            MapUrl = "https://maps.google.com/?q=10.7599,106.6813",
                            Name = "Oc Vinh Khanh 198",
                            Priority = 1,
                            TenantId = new Guid("f57c20b5-e865-40fb-bdbe-6fbf1a6fe6d0"),
                            TriggerRadiusMeters = 45,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("15fc7351-ee99-461d-8c56-8f7e181b5ee1"),
                            ApprovalStatus = 1,
                            CategoryKey = "food-street",
                            CategoryLabel = "Am thuc",
                            CooldownMinutes = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Gian hang bo la lot va nuong vi than, thich hop cho nhom sinh vien di an toi.",
                            ImageUrl = "https://example.com/images/bo-la-lot-co-lan.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 10.760400000000001,
                            Longitude = 106.6818,
                            MapUrl = "https://maps.google.com/?q=10.7604,106.6818",
                            Name = "Bo La Lot Co Lan",
                            Priority = 2,
                            TenantId = new Guid("f57c20b5-e865-40fb-bdbe-6fbf1a6fe6d0"),
                            TriggerRadiusMeters = 40,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f2ff8acf-f2ab-43b5-b967-1ac32b8c9a13"),
                            ApprovalStatus = 1,
                            CategoryKey = "food-street",
                            CategoryLabel = "An vat",
                            CooldownMinutes = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Quan nuoc va an vat nham toi uu cho luong khach tre quanh ky tuc xa.",
                            ImageUrl = "https://example.com/images/tra-chanh-sinh-vien-99.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 10.7608,
                            Longitude = 106.6808,
                            MapUrl = "https://maps.google.com/?q=10.7608,106.6808",
                            Name = "Tra Chanh Sinh Vien 99",
                            Priority = 3,
                            TenantId = new Guid("f57c20b5-e865-40fb-bdbe-6fbf1a6fe6d0"),
                            TriggerRadiusMeters = 35,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("ba80c3f5-fbbf-4586-b70c-55f70b2787de"),
                            ApprovalStatus = 1,
                            CategoryKey = "food-street",
                            CategoryLabel = "Do nuong",
                            CooldownMinutes = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Xe nuong dem voi cac mon thit xien, bach tuoc va rau cu nuong da toi.",
                            ImageUrl = "https://example.com/images/nuong-da-toi-24h.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 10.759499999999999,
                            Longitude = 106.68040000000001,
                            MapUrl = "https://maps.google.com/?q=10.7595,106.6804",
                            Name = "Nuong Da Toi 24h",
                            Priority = 4,
                            TenantId = new Guid("f57c20b5-e865-40fb-bdbe-6fbf1a6fe6d0"),
                            TriggerRadiusMeters = 30,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a4134f4e-0e41-447d-b791-403743213e0d"),
                            ApprovalStatus = 1,
                            CategoryKey = "food-street",
                            CategoryLabel = "Mon nuoc",
                            CooldownMinutes = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Quan chao suon mo som va ban muon, huong toi khach dia phuong va sinh vien o tro.",
                            ImageUrl = "https://example.com/images/chao-suon-dem-phu-dinh.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 10.7613,
                            Longitude = 106.6812,
                            MapUrl = "https://maps.google.com/?q=10.7613,106.6812",
                            Name = "Chao Suon Dem Phu Dinh",
                            Priority = 5,
                            TenantId = new Guid("f57c20b5-e865-40fb-bdbe-6fbf1a6fe6d0"),
                            TriggerRadiusMeters = 35,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("daeb6942-24d9-4d7e-89ec-b4836afefdae"),
                            ApprovalStatus = 1,
                            CategoryKey = "food-street",
                            CategoryLabel = "An vat",
                            CooldownMinutes = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Xe banh trang nuong phong cach Da Lat dat ngay lo vao khu tro sinh vien.",
                            ImageUrl = "https://example.com/images/banh-trang-nuong-ktx.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 10.7601,
                            Longitude = 106.6799,
                            MapUrl = "https://maps.google.com/?q=10.7601,106.6799",
                            Name = "Banh Trang Nuong KTX",
                            Priority = 6,
                            TenantId = new Guid("f57c20b5-e865-40fb-bdbe-6fbf1a6fe6d0"),
                            TriggerRadiusMeters = 25,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("c2bfa8d1-331d-4a6d-809f-01c1b248699c"),
                            ApprovalStatus = 1,
                            CategoryKey = "food-street",
                            CategoryLabel = "Mon nuoc",
                            CooldownMinutes = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "To bun thai vi chua cay la diem dung pho bien cua tuyen tham quan am thuc.",
                            ImageUrl = "https://example.com/images/bun-thai-hai-san-co-may.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 10.760999999999999,
                            Longitude = 106.68219999999999,
                            MapUrl = "https://maps.google.com/?q=10.7610,106.6822",
                            Name = "Bun Thai Hai San Co May",
                            Priority = 7,
                            TenantId = new Guid("f57c20b5-e865-40fb-bdbe-6fbf1a6fe6d0"),
                            TriggerRadiusMeters = 45,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("31ab5dfa-4db0-4f37-b280-d82d01f5c34c"),
                            ApprovalStatus = 1,
                            CategoryKey = "food-street",
                            CategoryLabel = "Trang mieng",
                            CooldownMinutes = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Gian kem cuon va mon trang mieng phuc vu du khach sau khi tham quan loat diem am thuc.",
                            ImageUrl = "https://example.com/images/kem-cuon-dem-sai-gon.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 10.7592,
                            Longitude = 106.6819,
                            MapUrl = "https://maps.google.com/?q=10.7592,106.6819",
                            Name = "Kem Cuon Dem Sai Gon",
                            Priority = 8,
                            TenantId = new Guid("f57c20b5-e865-40fb-bdbe-6fbf1a6fe6d0"),
                            TriggerRadiusMeters = 30,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("99d5b24a-8ef9-48cf-ad63-c4b5107f8b25"),
                            ApprovalStatus = 1,
                            CategoryKey = "food-street",
                            CategoryLabel = "Mon an dac san",
                            CooldownMinutes = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Hang pha lau mang phong vi duong pho, phu hop de mo phong noi dung am thuc dac trung.",
                            ImageUrl = "https://example.com/images/pha-lau-hem-99.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 10.7615,
                            Longitude = 106.6803,
                            MapUrl = "https://maps.google.com/?q=10.7615,106.6803",
                            Name = "Pha Lau Hem 99",
                            Priority = 9,
                            TenantId = new Guid("f57c20b5-e865-40fb-bdbe-6fbf1a6fe6d0"),
                            TriggerRadiusMeters = 40,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6aa7b67f-5bf0-4efd-8d20-c4c2648c63d8"),
                            ApprovalStatus = 1,
                            CategoryKey = "food-street",
                            CategoryLabel = "Mon an dac san",
                            CooldownMinutes = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Quan mi tron va hoanh thanh la diem ket noi giua khach du lich va sinh vien khu vuc.",
                            ImageUrl = "https://example.com/images/mi-tron-pho-dem.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 10.7606,
                            Longitude = 106.6828,
                            MapUrl = "https://maps.google.com/?q=10.7606,106.6828",
                            Name = "Mi Tron Pho Dem",
                            Priority = 10,
                            TenantId = new Guid("f57c20b5-e865-40fb-bdbe-6fbf1a6fe6d0"),
                            TriggerRadiusMeters = 35,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("GeoGuide.Cms.Models.PoiAudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text")
                        .HasColumnName("audio_url");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<string>("TtsContent")
                        .HasColumnType("text")
                        .HasColumnName("tts_content");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PoiId", "LanguageCode", "ContentType", "IsDeleted");

                    b.ToTable("poi_audios", null, t =>
                        {
                            t.HasCheckConstraint("CK_poi_audios_content_payload", "(content_type = 1 AND audio_url IS NOT NULL) OR (content_type = 2 AND tts_content IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f7fb649-d0ba-4bb7-9c05-d5db40cbdf01"),
                            AudioUrl = "https://example.com/audio/ben-thanh-market.mp3",
                            ContentType = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            LanguageCode = "vi",
                            PoiId = new Guid("9f0bbf75-a9fc-4a94-93a1-7c5ef0fc6a01"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("4ebc7203-0ca9-4312-b8f8-6f49169417e1"),
                            ContentType = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            LanguageCode = "en",
                            PoiId = new Guid("9f0bbf75-a9fc-4a94-93a1-7c5ef0fc6a01"),
                            TtsContent = "Ben Thanh Market is one of the city's most recognizable cultural and commercial landmarks.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5b5b6512-88af-4d0b-9f7b-85f3587b3d9e"),
                            AudioUrl = "https://example.com/audio/notre-dame-cathedral.mp3",
                            ContentType = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            LanguageCode = "vi",
                            PoiId = new Guid("458a1a0e-b524-4e95-92f4-684e80ea7b97"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("04fb45c2-dc26-476c-bcb9-b9695f0271da"),
                            ContentType = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            LanguageCode = "vi",
                            PoiId = new Guid("347dca58-717a-44cc-a470-0d12d2f039d1"),
                            TtsContent = "Diem dung chan dau tien cua tuyen am thuc, noi bat voi hai san binh dan va khong khi nhon nhip ve dem.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("GeoGuide.Cms.Models.PoiTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("poi_tenants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6eb3f509-c1a5-4d8d-9bb4-e307db6d0a75"),
                            IsActive = true,
                            Name = "Demo POI Tenant",
                            Slug = "demo-poi-tenant",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f57c20b5-e865-40fb-bdbe-6fbf1a6fe6d0"),
                            IsActive = true,
                            Name = "Vinh Khanh Food Street",
                            Slug = "vinh-khanh-food-street",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("GeoGuide.Cms.Models.Tour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tours", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a91b4ac0-0b3d-425f-8cd7-6b7f7ec6d501"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tuyen tham quan nhanh gom cho, nha tho va bao tang trung tam thanh pho.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sai Gon Diem Den Trung Tam",
                            ThumbnailUrl = "https://example.com/images/tour-sai-gon-central.jpg",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("d5a4a947-56fc-4671-a10f-d3cad0bdb8a2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tuyen am thuc dem cho khu Vinh Khanh va cac diem an uong gan ky tuc xa.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Vinh Khanh Food Walk",
                            ThumbnailUrl = "https://example.com/images/tour-vinh-khanh-food-walk.jpg",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 16, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("GeoGuide.Cms.Models.TourPoiMapping", b =>
                {
                    b.Property<Guid>("TourId")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_id");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.HasKey("TourId", "PoiId");

                    b.HasIndex("PoiId");

                    b.ToTable("tour_poi_mappings", (string)null);

                    b.HasData(
                        new
                        {
                            TourId = new Guid("a91b4ac0-0b3d-425f-8cd7-6b7f7ec6d501"),
                            PoiId = new Guid("9f0bbf75-a9fc-4a94-93a1-7c5ef0fc6a01"),
                            OrderIndex = 1
                        },
                        new
                        {
                            TourId = new Guid("a91b4ac0-0b3d-425f-8cd7-6b7f7ec6d501"),
                            PoiId = new Guid("458a1a0e-b524-4e95-92f4-684e80ea7b97"),
                            OrderIndex = 2
                        },
                        new
                        {
                            TourId = new Guid("a91b4ac0-0b3d-425f-8cd7-6b7f7ec6d501"),
                            PoiId = new Guid("a76542f8-e34f-45ee-96c9-0e3961c4ca30"),
                            OrderIndex = 3
                        },
                        new
                        {
                            TourId = new Guid("d5a4a947-56fc-4671-a10f-d3cad0bdb8a2"),
                            PoiId = new Guid("347dca58-717a-44cc-a470-0d12d2f039d1"),
                            OrderIndex = 1
                        },
                        new
                        {
                            TourId = new Guid("d5a4a947-56fc-4671-a10f-d3cad0bdb8a2"),
                            PoiId = new Guid("15fc7351-ee99-461d-8c56-8f7e181b5ee1"),
                            OrderIndex = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("cms_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("cms_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("cms_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("cms_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("cms_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("cms_user_tokens", (string)null);
                });

            modelBuilder.Entity("GeoGuide.Cms.Models.ApplicationUser", b =>
                {
                    b.HasOne("GeoGuide.Cms.Models.PoiTenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GeoGuide.Cms.Models.PlaybackLog", b =>
                {
                    b.HasOne("GeoGuide.Cms.Models.Poi", "Poi")
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("GeoGuide.Cms.Models.Poi", b =>
                {
                    b.HasOne("GeoGuide.Cms.Models.PoiTenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GeoGuide.Cms.Models.PoiAudio", b =>
                {
                    b.HasOne("GeoGuide.Cms.Models.Poi", "Poi")
                        .WithMany("Audios")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("GeoGuide.Cms.Models.TourPoiMapping", b =>
                {
                    b.HasOne("GeoGuide.Cms.Models.Poi", "Poi")
                        .WithMany("TourMappings")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoGuide.Cms.Models.Tour", "Tour")
                        .WithMany("PoiMappings")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GeoGuide.Cms.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GeoGuide.Cms.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoGuide.Cms.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GeoGuide.Cms.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoGuide.Cms.Models.Poi", b =>
                {
                    b.Navigation("Audios");

                    b.Navigation("TourMappings");
                });

            modelBuilder.Entity("GeoGuide.Cms.Models.Tour", b =>
                {
                    b.Navigation("PoiMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
