// <auto-generated />
using System;
using GeoGuide.Cms.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoGuide.Cms.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409073359_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoGuide.Cms.Models.PlaybackLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_id");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trigger_type");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.ToTable("playback_logs", (string)null);
                });

            modelBuilder.Entity("GeoGuide.Cms.Models.Poi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audio_url");

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_key");

                    b.Property<string>("CategoryLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category_label");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language_code");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MapUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("map_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("TriggerRadiusMeters")
                        .HasColumnType("integer")
                        .HasColumnName("trigger_radius_meters");

                    b.Property<string>("TtsScript")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tts_script");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("pois", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f0bbf75-a9fc-4a94-93a1-7c5ef0fc6a01"),
                            AudioUrl = "https://example.com/audio/ben-thanh-market.mp3",
                            CategoryKey = "attraction",
                            CategoryLabel = "Tham quan",
                            Description = "Khu cho noi tieng o trung tam TP.HCM.",
                            ImageUrl = "https://images.unsplash.com/photo-1555921015-5532091f6026",
                            IsActive = true,
                            LanguageCode = "vi-VN",
                            Latitude = 10.772,
                            Longitude = 106.6983,
                            MapUrl = "https://maps.google.com/?q=10.7720,106.6983",
                            Name = "Ben Thanh Market",
                            Priority = 1,
                            TriggerRadiusMeters = 80,
                            TtsScript = "Day la cho Ben Thanh, mot bieu tuong van hoa va du lich cua thanh pho.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("458a1a0e-b524-4e95-92f4-684e80ea7b97"),
                            AudioUrl = "https://example.com/audio/notre-dame-cathedral.mp3",
                            CategoryKey = "attraction",
                            CategoryLabel = "Tham quan",
                            Description = "Nha tho Duc Ba Sai Gon voi kien truc Phap tieu bieu.",
                            ImageUrl = "https://images.unsplash.com/photo-1583417267826-aebc4d1542e1",
                            IsActive = true,
                            LanguageCode = "vi-VN",
                            Latitude = 10.7798,
                            Longitude = 106.699,
                            MapUrl = "https://maps.google.com/?q=10.7798,106.6990",
                            Name = "Notre-Dame Cathedral",
                            Priority = 2,
                            TriggerRadiusMeters = 90,
                            TtsScript = "Nha tho Duc Ba la mot diem nhan kien truc va lich su ngay giua trung tam thanh pho.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5807657e-240d-42cb-b6e8-b46fd35652ce"),
                            AudioUrl = "https://example.com/audio/tao-dan-park.mp3",
                            CategoryKey = "park",
                            CategoryLabel = "Cong vien",
                            Description = "Cong vien xanh phu hop cho di bo va thu gian.",
                            ImageUrl = "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
                            IsActive = true,
                            LanguageCode = "vi-VN",
                            Latitude = 10.777799999999999,
                            Longitude = 106.6927,
                            MapUrl = "https://maps.google.com/?q=10.7778,106.6927",
                            Name = "Tao Dan Park",
                            Priority = 3,
                            TriggerRadiusMeters = 100,
                            TtsScript = "Cong vien Tao Dan la khoang xanh hien hoi, noi nguoi dan dia phuong thuong tap the duc vao sang som.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a76542f8-e34f-45ee-96c9-0e3961c4ca30"),
                            AudioUrl = "https://example.com/audio/hcm-city-museum.mp3",
                            CategoryKey = "museum",
                            CategoryLabel = "Bao tang",
                            Description = "Bao tang gioi thieu lich su va van hoa thanh pho.",
                            ImageUrl = "https://images.unsplash.com/photo-1518998053901-5348d3961a04",
                            IsActive = true,
                            LanguageCode = "vi-VN",
                            Latitude = 10.7765,
                            Longitude = 106.70099999999999,
                            MapUrl = "https://maps.google.com/?q=10.7765,106.7010",
                            Name = "Ho Chi Minh City Museum",
                            Priority = 4,
                            TriggerRadiusMeters = 75,
                            TtsScript = "Bao tang Thanh pho Ho Chi Minh luu giu nhieu tu lieu va hien vat quan trong.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("GeoGuide.Cms.Models.PlaybackLog", b =>
                {
                    b.HasOne("GeoGuide.Cms.Models.Poi", "Poi")
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });
#pragma warning restore 612, 618
        }
    }
}
